version: "3.9"

services:
  database:
    build: ./database
    container_name: postgres_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal_net

  backend:
    build: ./backend
    container_name: node_backend
    env_file: .env
    ports:
      - "${BACKEND_PORT}:5000"
    depends_on:
      - database
    networks:
      - internal_net

  frontend:
    build: ./frontend
    container_name: next_frontend
    env_file: .env
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    networks:
      - internal_net

volumes:
  db_data:

networks:
  internal_net:
    driver: bridge
